version: '3.8'

services:
  backend:
    # Use the image built and pushed by GitHub Actions
    image: ghcr.io/nabobery/ragchatbot-backend:latest
    environment:
      # These are examples - set the actual values in Sevalla
      - DJANGO_SETTINGS_MODULE=core.settings
    # Tell Sevalla the backend service listens internally on port 8000
    # Sevalla will handle external mapping/routing.
    ports:
      - "8000"

  frontend:
    # Use the image built and pushed by GitHub Actions
    image: ghcr.io/nabobery/ragchatbot-frontend:latest
    # Environment variables MUST be set in the Sevalla UI
    environment:
      # This needs to point to the PUBLIC URL of your backend service on Sevalla
      - NEXT_PUBLIC_API_BASE_URL=https://your-backend-domain.sevalla.app/api/documents # Replace with actual Sevalla backend URL
    # Tell Sevalla the frontend service listens internally on port 3000
    ports:
      - "3000"