name: Deploy Backend to Sevalla

on:
  push:
    branches: ["main"] # Trigger only on pushes to the main branch
    paths:
      - 'backend/**'          # Trigger if anything changes in the backend directory
      - '.github/workflows/deploy-backend.yml' # Trigger if this workflow file changes

jobs:
  trigger-sevalla-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Sevalla Deployment Webhook
        run: |
          echo "Triggering Sevalla deployment for backend..."
          curl -X POST ${{ secrets.SEVALLA_WEBHOOK_URL }}
          echo "Sevalla webhook triggered."